### ISSUE TITLE
Integration with sophisticated backpacks breaks after mod update

### ISSUE THREAD

**Issue by unikmhz** [wisp-forest/accessories#210]
MC version: 1.21.1
NeoForge version: 21.1.115
Launcher: Prism

### Synopsis

After updating accessories to 1.1.0-beta.26+1.21.1, and curios compat layer to 0.beta.21, pressing the bound hotkey to open a backpack worn in back slot no longer opens the backpack UI. Additionally, some backpack upgrades (like auto-refill or auto-import) stop working.

Said hotkey still works when the backpack is moved from accessory slot to a hotbar.

When downgrading accessories and CCLayer, said hotkey resumes working in accessory slot.

### Mod versions

Accessories: 1.1.0-beta.24+1.21.1 -> 1.1.0-beta.26+1.21.1
Curios Compatibility Layer: beta 20 -> beta 21
Sophisticated Core: 1.2.3
Sophisticated Backpacks: 3.23.3

**Comment by penturt** [comment]
@Dragon-Seeker, reporting possibiliy the same issue with the latest release/fix. Not sure if its just Accessories but when i try to access the Curios tab provided by [L2 Library](https://www.curseforge.com/minecraft/mc-mods/l2library) the mouse rubber bands, see attach video. Was not happening before.

https://github.com/user-attachments/assets/feea7036-a5c8-404b-8dfb-73cd7fe578df

**Comment by Dragon-Seeker** [comment]
Ah found the issue as I forget to return a value for predicate checking for a given stack leading to Sophisticated backpacks not finding the back slot, will release fix for such later today.

**Comment by Dragon-Seeker** [comment]
Ok update for the CCLayer has been pushed to modrinth and curseforge that should solve this issues

**Comment by unikmhz** [comment]
Tried with latest accessories (beta 26) and CCLayer (beta 22). But hotkey still doesn't work.

**Comment by Dragon-Seeker** [comment]
Swear it worked in dev but found another bug that I confirmed fix the issue with beta 23
